### ISSUE TITLE
Error getting the transaction

### ISSUE THREAD

**Issue by Lyle-liang** [straumat/blockchain2graph#223]
docker: 3.1-snapshot.

I get the error that always exist after restarted.  transaction id change fast. like this:

![image](https://user-images.githubusercontent.com/14850448/44781766-d1155080-abb7-11e8-84da-3029e3e409eb.png)

Thanks.

**Comment by straumat** [comment]
Sorry, I can't reproduce. There may be an encoding problem with docker.
can you change docker compose to use my public server ?
```
 environment:
      - BITCOINCORE_HOSTNAME=5.196.65.205
``` 

Can you send me more logs ? they may be in the data/ directory ?

**Comment by Lyle-liang** [comment]
I will try again, and wait and see how the result.

**Comment by Lyle-liang** [comment]
@straumat If it works well, and how long does it take for the data to be fully parsed ?

**Comment by straumat** [comment]
```
version: '2'
services:
  # ====================================================================================================================
  # https://hub.docker.com/_/neo4j/
  neo4j:
    image: neo4j:3.4.6
    volumes:
      - ./data/neo4j:/var/lib/neo4j/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
  # ====================================================================================================================
  # https://hub.docker.com/r/straumat/blockchain2graph-bitcoin-neo4j/
  blockchain2graph-bitcoin-neo4j:
    image: straumat/blockchain2graph-bitcoin-neo4j:3.1-SNAPSHOT
    ports:
      - 8080:8080
    links:
      - neo4j
    environment:
      - BITCOINCORE_HOSTNAME=5.196.65.205
      - BITCOINCORE_USERNAME=bitcoinrpc
      - BITCOINCORE_PASSWORD=JRkDy3tgCYdmCEqY1VdfdfhTswiRva
      - SPRING_DATA_NEO4J_URI=bolt://neo4j:neo4j123@neo4j:7687
```
It can take severak weekds... depends on your harware
