### ISSUE TITLE
Neo4j doesn't have the blockchain data

### ISSUE THREAD

**Issue by nikhilh-20** [straumat/blockchain2graph#316]
I installed Docker on an Ubuntu 18.04 VM on my Windows 10 Home host. I used the `docker-compose-blockchain2graph-bitcoin-neo4j.yml`. I modified the `bitcoin-core` to use `latest` instead of `0.18.0`. Here's the modified file:

```
version: '2'
services:
  # ====================================================================================================================
  # https://hub.docker.com/r/ruimarinho/bitcoin-core/
  bitcoin-core:
    image: ruimarinho/bitcoin-core:latest
    volumes:
      - ./data/bitcoin-core:/home/bitcoin/.bitcoin
    ports:
      - 8332:8332
    command:
      -server=1
      -rest=1
      -rpcuser=xxx
      -rpcpassword=xxx
      -txindex=1
      -rpcallowip=0.0.0.0/0
      -rpcallowip=::/0
  # ====================================================================================================================
  # https://hub.docker.com/_/neo4j/
  neo4j:
    image: neo4j:3.5.5
    volumes:
      - ./data/neo4j:/var/lib/neo4j/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/xxx
  # ====================================================================================================================
  # https://hub.docker.com/r/straumat/blockchain2graph-bitcoin-neo4j/
  blockchain2graph-bitcoin-neo4j:
    image: straumat/blockchain2graph-bitcoin-neo4j:3.1
    ports:
      - 8080:8080
    links:
      - bitcoin-core
      - neo4j
    environment:
      - BITCOINCORE_HOSTNAME=bitcoin-core # Public server : 5.196.65.205
      - BITCOINCORE_USERNAME=xxx
      - BITCOINCORE_PASSWORD=xxx
      - SPRING_DATA_NEO4J_URI=bolt://neo4j:xxx@neo4j:7687
```

I commented out the `neo4j` and `blockchain2graph-bitcoin-neo4j` sections and downloaded the entire Bitcoin blockchain. Once I was done with downloading, then I commented in `neo4j` and `blockchain2graph-bitcoin-neo4j` sections.

Logs:
```
dockserv@ubuntu:~/BitcoinDocker$ docker-compose up
Pulling neo4j (neo4j:3.5.5)...
3.5.5: Pulling from library/neo4j
e7c96db7181b: Pull complete
f910a506b6cb: Pull complete
b6abafe80f63: Pull complete
b95a7fd32595: Pull complete
0a47539269b0: Pull complete
c0fcaae73c48: Pull complete
8cc1caa34b16: Pull complete
Digest: sha256:5612f1f907115fbeca93ae1a989b35d8c6a80e8ed12d279eba68ed3178eb4436
Status: Downloaded newer image for neo4j:3.5.5
Pulling blockchain2graph-bitcoin-neo4j (straumat/blockchain2graph-bitcoin-neo4j:3.1)...
3.1: Pulling from straumat/blockchain2graph-bitcoin-neo4j
4fe2ade4980c: Pull complete
6fc58a8d4ae4: Pull complete
819f4a45746c: Pull complete
62a34cc58148: Pull complete
Digest: sha256:837095a66cf4ba9e094de6acbf6fb75f1e3020503b6a9d57e1ddcccd383b3ec9
Status: Downloaded newer image for straumat/blockchain2graph-bitcoin-neo4j:3.1
Starting bitcoindocker_bitcoin-core_1 ... done
Creating bitcoindocker_neo4j_1        ... done
Creating bitcoindocker_blockchain2graph-bitcoin-neo4j_1 ... done
Attaching to bitcoindocker_bitcoin-core_1, bitcoindocker_neo4j_1, bitcoindocker_blockchain2graph-bitcoin-neo4j_1
bitcoin-core_1                    | /entrypoint.sh: assuming arguments for bitcoind
bitcoin-core_1                    | /entrypoint.sh: setting data directory to /home/bitcoin/.bitcoin
bitcoin-core_1                    | 
bitcoin-core_1                    | 2019-09-19T18:10:26Z Bitcoin Core version v0.18.1 (release build)
bitcoin-core_1                    | 2019-09-19T18:10:26Z Assuming ancestors of block 0000000000000000000f1c54590ee18d15ec70e68c8cd4cfbadb1b4f11697eee have valid signatures.
bitcoin-core_1                    | 2019-09-19T18:10:26Z Setting nMinimumChainWork=0000000000000000000000000000000000000000051dc8b82f450202ecb3d471
bitcoin-core_1                    | 2019-09-19T18:10:26Z Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
bitcoin-core_1                    | 2019-09-19T18:10:26Z Using RdSeed as additional entropy source
bitcoin-core_1                    | 2019-09-19T18:10:26Z Using RdRand as an additional entropy source
bitcoin-core_1                    | 2019-09-19T18:10:26Z Default data directory /home/bitcoin/.bitcoin
bitcoin-core_1                    | 2019-09-19T18:10:26Z Using data directory /home/bitcoin/.bitcoin
bitcoin-core_1                    | 2019-09-19T18:10:26Z Config file: /home/bitcoin/.bitcoin/bitcoin.conf (not found, skipping)
bitcoin-core_1                    | 2019-09-19T18:10:26Z Using at most 125 automatic connections (1048576 file descriptors available)
bitcoin-core_1                    | 2019-09-19T18:10:26Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
bitcoin-core_1                    | 2019-09-19T18:10:26Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
bitcoin-core_1                    | 2019-09-19T18:10:26Z Using 8 threads for script verification
bitcoin-core_1                    | 2019-09-19T18:10:26Z WARNING: option -rpcallowip was specified without -rpcbind; this doesn't usually make sense
bitcoin-core_1                    | 2019-09-19T18:10:26Z libevent: getaddrinfo: address family for nodename not supported
bitcoin-core_1                    | 2019-09-19T18:10:26Z Binding RPC on address ::1 port 8332 failed.
bitcoin-core_1                    | 2019-09-19T18:10:26Z scheduler thread start
bitcoin-core_1                    | 2019-09-19T18:10:26Z HTTP: creating work queue of depth 16
bitcoin-core_1                    | 2019-09-19T18:10:26Z Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcauth for rpcauth auth generation.
bitcoin-core_1                    | 2019-09-19T18:10:26Z HTTP: starting 4 worker threads
bitcoin-core_1                    | 2019-09-19T18:10:26Z Using wallet directory /home/bitcoin/.bitcoin
bitcoin-core_1                    | 2019-09-19T18:10:26Z init message: Verifying wallet(s)...
bitcoin-core_1                    | 2019-09-19T18:10:26Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
bitcoin-core_1                    | 2019-09-19T18:10:26Z Using wallet /home/bitcoin/.bitcoin
bitcoin-core_1                    | 2019-09-19T18:10:26Z BerkeleyEnvironment::Open: LogDir=/home/bitcoin/.bitcoin/database ErrorFile=/home/bitcoin/.bitcoin/db.log
bitcoin-core_1                    | 2019-09-19T18:10:26Z init message: Loading banlist...
bitcoin-core_1                    | 2019-09-19T18:10:26Z Cache configuration:
bitcoin-core_1                    | 2019-09-19T18:10:26Z * Using 2.0 MiB for block index database
bitcoin-core_1                    | 2019-09-19T18:10:26Z * Using 56.0 MiB for transaction index database
bitcoin-core_1                    | 2019-09-19T18:10:26Z * Using 8.0 MiB for chain state database
bitcoin-core_1                    | 2019-09-19T18:10:26Z * Using 384.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
bitcoin-core_1                    | 2019-09-19T18:10:26Z init message: Loading block index...
bitcoin-core_1                    | 2019-09-19T18:10:26Z Opening LevelDB in /home/bitcoin/.bitcoin/blocks/index
bitcoin-core_1                    | 2019-09-19T18:10:26Z Opened LevelDB successfully
bitcoin-core_1                    | 2019-09-19T18:10:26Z Using obfuscation key for /home/bitcoin/.bitcoin/blocks/index: 0000000000000000
neo4j_1                           | command failed: the provided initial password was not set because existing Neo4j users were detected at `/var/lib/neo4j/data/dbms/auth`. Please remove the existing `auth` file if you want to reset your database to only have a default user with the provided password.
blockchain2graph-bitcoin-neo4j_1  | 
blockchain2graph-bitcoin-neo4j_1  | =============================================================================================================
blockchain2graph-bitcoin-neo4j_1  | ___.   .__                 __          .__           .__        ________                             .__
blockchain2graph-bitcoin-neo4j_1  | \_ |__ |  |   ____   ____ |  | __ ____ |  |__ _____  |__| ____  \_____  \   ________________  ______ |  |__  
blockchain2graph-bitcoin-neo4j_1  |  | __ \|  |  /  _ \_/ ___\|  |/ // ___\|  |  \\__  \ |  |/    \  /  ____/  / ___\_  __ \__  \ \____ \|  |  \ 
blockchain2graph-bitcoin-neo4j_1  |  | \_\ \  |_(  <_> )  \___|    <\  \___|   Y  \/ __ \|  |   |  \/       \ / /_/  >  | \// __ \|  |_> >   Y  \
blockchain2graph-bitcoin-neo4j_1  |  |___  /____/\____/ \___  >__|_ \\___  >___|  (____  /__|___|  /\_______ \\___  /|__|  (____  /   __/|___|  /
blockchain2graph-bitcoin-neo4j_1  |      \/                 \/     \/    \/     \/     \/        \/         \/_____/            \/|__|        \/
blockchain2graph-bitcoin-neo4j_1  | 3.1
blockchain2graph-bitcoin-neo4j_1  | =============================================================================================================
blockchain2graph-bitcoin-neo4j_1  | 
neo4j_1                           | Active database: graph.db
neo4j_1                           | Directories in use:
neo4j_1                           |   home:         /var/lib/neo4j
neo4j_1                           |   config:       /var/lib/neo4j/conf
neo4j_1                           |   logs:         /logs
neo4j_1                           |   plugins:      /var/lib/neo4j/plugins
neo4j_1                           |   import:       /var/lib/neo4j/import
neo4j_1                           |   data:         /var/lib/neo4j/data
neo4j_1                           |   certificates: /var/lib/neo4j/certificates
neo4j_1                           |   run:          /var/lib/neo4j/run
neo4j_1                           | Starting Neo4j.
blockchain2graph-bitcoin-neo4j_1  | 18:10:30 - Starting Application v3.1 on 023d10b2270e with PID 1 (/app.jar started by root in /)
blockchain2graph-bitcoin-neo4j_1  | 18:10:30 - No active profile set, falling back to default profiles: default
bitcoin-core_1                    | 2019-09-19T18:10:30Z LoadBlockIndexDB: last block file = 1799
bitcoin-core_1                    | 2019-09-19T18:10:30Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=96, size=112186724, heights=595514...595640, time=2019-09-18...2019-09-19)
bitcoin-core_1                    | 2019-09-19T18:10:30Z Checking all blk files are present...
bitcoin-core_1                    | 2019-09-19T18:10:30Z Opening LevelDB in /home/bitcoin/.bitcoin/chainstate
bitcoin-core_1                    | 2019-09-19T18:10:30Z Opened LevelDB successfully
bitcoin-core_1                    | 2019-09-19T18:10:30Z Using obfuscation key for /home/bitcoin/.bitcoin/chainstate: 42acffcb9675ad12
bitcoin-core_1                    | 2019-09-19T18:10:31Z Loaded best chain: hashBestChain=0000000000000000000496db5b6fd4eeb0c220bfeeac5b60fb705b1dbb345983 height=595640 date=2019-09-19T18:00:32Z progress=0.999995
bitcoin-core_1                    | 2019-09-19T18:10:31Z init message: Rewinding blocks...
neo4j_1                           | 2019-09-19 18:10:32.013+0000 WARN  Unknown config option: causal_clustering.discovery_listen_address
neo4j_1                           | 2019-09-19 18:10:32.017+0000 WARN  Unknown config option: causal_clustering.raft_advertised_address
neo4j_1                           | 2019-09-19 18:10:32.018+0000 WARN  Unknown config option: causal_clustering.raft_listen_address
neo4j_1                           | 2019-09-19 18:10:32.018+0000 WARN  Unknown config option: ha.host.coordination
neo4j_1                           | 2019-09-19 18:10:32.018+0000 WARN  Unknown config option: causal_clustering.transaction_advertised_address
neo4j_1                           | 2019-09-19 18:10:32.019+0000 WARN  Unknown config option: causal_clustering.discovery_advertised_address
neo4j_1                           | 2019-09-19 18:10:32.019+0000 WARN  Unknown config option: ha.host.data
neo4j_1                           | 2019-09-19 18:10:32.019+0000 WARN  Unknown config option: causal_clustering.transaction_listen_address
neo4j_1                           | 2019-09-19 18:10:32.034+0000 INFO  ======== Neo4j 3.5.5 ========
neo4j_1                           | 2019-09-19 18:10:32.044+0000 INFO  Starting...
bitcoin-core_1                    | 2019-09-19T18:10:32Z init message: Verifying blocks...
bitcoin-core_1                    | 2019-09-19T18:10:32Z Verifying last 6 blocks at level 3
bitcoin-core_1                    | 2019-09-19T18:10:32Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
bitcoin-core_1                    | 2019-09-19T18:10:34Z No coin database inconsistencies in last 6 blocks (15630 transactions)
bitcoin-core_1                    | 2019-09-19T18:10:34Z  block index            7855ms
bitcoin-core_1                    | 2019-09-19T18:10:34Z Opening LevelDB in /home/bitcoin/.bitcoin/indexes/txindex
bitcoin-core_1                    | 2019-09-19T18:10:34Z Opened LevelDB successfully
bitcoin-core_1                    | 2019-09-19T18:10:34Z Using obfuscation key for /home/bitcoin/.bitcoin/indexes/txindex: 0000000000000000
bitcoin-core_1                    | 2019-09-19T18:10:34Z init message: Loading wallet...
bitcoin-core_1                    | 2019-09-19T18:10:34Z txindex thread start
bitcoin-core_1                    | 2019-09-19T18:10:34Z BerkeleyEnvironment::Open: LogDir=/home/bitcoin/.bitcoin/database ErrorFile=/home/bitcoin/.bitcoin/db.log
bitcoin-core_1                    | 2019-09-19T18:10:34Z txindex is enabled at height 595640
bitcoin-core_1                    | 2019-09-19T18:10:34Z txindex thread exit
bitcoin-core_1                    | 2019-09-19T18:10:34Z [default wallet] nFileVersion = 180100
bitcoin-core_1                    | 2019-09-19T18:10:34Z [default wallet] Keys: 2001 plaintext, 0 encrypted, 2001 w/ metadata, 2001 total. Unknown wallet records: 0
bitcoin-core_1                    | 2019-09-19T18:10:34Z [default wallet] Wallet completed loading in              47ms
bitcoin-core_1                    | 2019-09-19T18:10:34Z [default wallet] setKeyPool.size() = 2000
bitcoin-core_1                    | 2019-09-19T18:10:34Z [default wallet] mapWallet.size() = 0
bitcoin-core_1                    | 2019-09-19T18:10:34Z [default wallet] mapAddressBook.size() = 0
bitcoin-core_1                    | 2019-09-19T18:10:34Z mapBlockIndex.size() = 595641
bitcoin-core_1                    | 2019-09-19T18:10:34Z nBestHeight = 595640
bitcoin-core_1                    | 2019-09-19T18:10:34Z torcontrol thread start
bitcoin-core_1                    | 2019-09-19T18:10:34Z Bound to [::]:8333
bitcoin-core_1                    | 2019-09-19T18:10:34Z Bound to 0.0.0.0:8333
bitcoin-core_1                    | 2019-09-19T18:10:34Z init message: Loading P2P addresses...
bitcoin-core_1                    | 2019-09-19T18:10:34Z Leaving InitialBlockDownload (latching to false)
bitcoin-core_1                    | 2019-09-19T18:10:34Z Loaded 60492 addresses from peers.dat  340ms
bitcoin-core_1                    | 2019-09-19T18:10:34Z init message: Starting network threads...
bitcoin-core_1                    | 2019-09-19T18:10:34Z init message: Done loading
bitcoin-core_1                    | 2019-09-19T18:10:34Z opencon thread start
bitcoin-core_1                    | 2019-09-19T18:10:34Z msghand thread start
bitcoin-core_1                    | 2019-09-19T18:10:34Z addcon thread start
bitcoin-core_1                    | 2019-09-19T18:10:34Z dnsseed thread start
bitcoin-core_1                    | 2019-09-19T18:10:34Z net thread start
bitcoin-core_1                    | 2019-09-19T18:10:35Z New outbound peer connected: version: 70015, blocks=595640, peer=0
bitcoin-core_1                    | 2019-09-19T18:10:35Z Imported mempool transactions from disk: 1386 succeeded, 0 failed, 0 expired, 0 already there
neo4j_1                           | 2019-09-19 18:10:36.340+0000 INFO  Bolt enabled on 0.0.0.0:7687.
blockchain2graph-bitcoin-neo4j_1  | 18:10:36 - Creating constraints and indexes...
blockchain2graph-bitcoin-neo4j_1  | 18:10:36 - Direct driver instance 210281271 created for server address neo4j:7687
blockchain2graph-bitcoin-neo4j_1  | 18:10:38 - Constraints and indexes created
neo4j_1                           | 2019-09-19 18:10:38.492+0000 INFO  Started.
blockchain2graph-bitcoin-neo4j_1  | 18:10:39 - Started Application in 9.529 seconds (JVM running for 10.339)
neo4j_1                           | 2019-09-19 18:10:39.970+0000 INFO  Remote interface available at http://localhost:7474/
bitcoin-core_1                    | 2019-09-19T18:10:45Z Loading addresses from DNS seeds (could take a while)
bitcoin-core_1                    | 2019-09-19T18:10:47Z New outbound peer connected: version: 70015, blocks=595640, peer=1
bitcoin-core_1                    | 2019-09-19T18:10:48Z New outbound peer connected: version: 70015, blocks=595640, peer=2
bitcoin-core_1                    | 2019-09-19T18:10:55Z 164 addresses found from DNS seeds
bitcoin-core_1                    | 2019-09-19T18:10:55Z dnsseed thread exit
bitcoin-core_1                    | 2019-09-19T18:11:27Z New outbound peer connected: version: 70015, blocks=595640, peer=4
bitcoin-core_1                    | 2019-09-19T18:11:27Z New outbound peer connected: version: 70015, blocks=595640, peer=5
bitcoin-core_1                    | 2019-09-19T18:11:28Z New outbound peer connected: version: 70015, blocks=595640, peer=6
bitcoin-core_1                    | 2019-09-19T18:11:28Z New outbound peer connected: version: 70015, blocks=595640, peer=7
neo4j_1                           | 2019-09-19 18:11:31.210+0000 WARN  The client is unauthorized due to authentication failure.
bitcoin-core_1                    | 2019-09-19T18:11:35Z New outbound peer connected: version: 70015, blocks=595640, peer=8
bitcoin-core_1                    | 2019-09-19T18:11:41Z New outbound peer connected: version: 70015, blocks=595640, peer=9
bitcoin-core_1                    | 2019-09-19T18:12:34Z UpdateTip: new best=0000000000000000000abe0b2a1d7d06993526d6b8e12d4213313e86d83349af height=595641 version=0x20000000 log2_work=91.107759 tx=456817418 date='2019-09-19T18:12:18Z' progress=1.000000 cache=2.0MiB(15069txo) warning='53 of last 100 blocks have unexpected version'
```

I expected the the blockchain data to be visible in Neo4j as a graph once the above `docker-compose up` was executed. But I see nothing. This is my first time meddling with Neo4j and the blockchain, so I'm not sure if there's additional steps to be taken.

```
dockserv@ubuntu:/var/lib$ sudo netstat -antp | grep bitcoin
```

OS information:
```
dockserv@ubuntu:~$ uname -a
Linux ubuntu 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Browser: Firefox Quantum 69.0 (64-bit)

**Comment by nikhilh-20** [comment]
Okay, this was resolved after I added `rpcbind` parameter to `docker-compose.yml`.

**Comment by straumat** [comment]
Can you copy.paste your docker file please because it's not working with minre :(

**Comment by nikhilh-20** [comment]
Here you go:
```
version: '2'
services:
  # ====================================================================================================================
  # https://hub.docker.com/r/ruimarinho/bitcoin-core/
  bitcoin-core:
    image: ruimarinho/bitcoin-core:latest
    volumes:
      - ./data/bitcoin-core:/home/bitcoin/.bitcoin
    ports:
      - 8332:8332
    command:
      -server=1
      -rest=1
      -rpcuser=xxx
      -rpcpassword=xxx
      -txindex=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=127.0.0.1
      -rpcbind=bitcoin-core
      -rpcallowip=::/0
  # ====================================================================================================================
  # https://hub.docker.com/_/neo4j/
  neo4j:
    image: neo4j:3.5.5
    volumes:
      - ./data/neo4j:/var/lib/neo4j/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=xxx/xxx
  # ====================================================================================================================
  # https://hub.docker.com/r/straumat/blockchain2graph-bitcoin-neo4j/
  blockchain2graph-bitcoin-neo4j:
    image: straumat/blockchain2graph-bitcoin-neo4j:3.1
    ports:
      - 8080:8080
    links:
      - bitcoin-core
      - neo4j
    environment:
      - BITCOINCORE_HOSTNAME=bitcoin-core # Public server : 5.196.65.205
      - BITCOINCORE_USERNAME=bitcoinrpc
      - BITCOINCORE_PASSWORD=xxx
      - SPRING_DATA_NEO4J_URI=bolt://xxx:xxx@neo4j:7687
```

At this time, I'm not sure if it's working 100%. The below status has been holding for the past 7 hours:
![image](https://user-images.githubusercontent.com/9674215/65295254-ca44dd00-db2e-11e9-9637-2c219e06fdef.png)
Also, refer #317
